FROM oven/bun:latest

WORKDIR /app

# Declare build-time arguments
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APPWRITE_ENDPOINT
ARG NEXT_PUBLIC_APPWRITE_PROJECT
ARG NEXT_PUBLIC_APPWRITE_DATABASE_ID
ARG NEXT_PUBLIC_APPWRITE_WORKSPACES_ID
ARG NEXT_PUBLIC_APPWRITE_STORAGE_ID
ARG NEXT_PUBLIC_APPWRITE_MEMBERS_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECTS_ID

# Export them as environment variables so `bun run build` can access them
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APPWRITE_ENDPOINT=$NEXT_PUBLIC_APPWRITE_ENDPOINT
ENV NEXT_PUBLIC_APPWRITE_PROJECT=$NEXT_PUBLIC_APPWRITE_PROJECT
ENV NEXT_PUBLIC_APPWRITE_DATABASE_ID=$NEXT_PUBLIC_APPWRITE_DATABASE_ID
ENV NEXT_PUBLIC_APPWRITE_WORKSPACES_ID=$NEXT_PUBLIC_APPWRITE_WORKSPACES_ID
ENV NEXT_PUBLIC_APPWRITE_STORAGE_ID=$NEXT_PUBLIC_APPWRITE_STORAGE_ID
ENV NEXT_PUBLIC_APPWRITE_MEMBERS_ID=$NEXT_PUBLIC_APPWRITE_MEMBERS_ID
ENV NEXT_PUBLIC_APPWRITE_PROJECTS_ID=$NEXT_PUBLIC_APPWRITE_PROJECTS_ID

COPY package.json ./
COPY bun.lock ./


RUN bun install
COPY . .

RUN bun run build

EXPOSE 3000

CMD bun run start
